# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rm87321-checkpoint3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_2fa0288e5d6c440c95f399687f1bc05f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e2dc304448364693a39b40f0a8c04f2e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2fa0288e5d6c440c95f399687f1bc05f }}/pedrotony/checkpoint3:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rm87321-checkpoint3'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_efd091a6d9c441179910e1d90265919b }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2fa0288e5d6c440c95f399687f1bc05f }}/pedrotony/checkpoint3:${{ github.sha }}'